#macro CB_RENDER_VERSION  "3.0.0"
#macro CB_RENDER_DATE     "2024-06-16"

#macro CB_LIGHTING_DISABLE_LIGHTING    0
#macro CB_LIGHTING_NO_SHADOWED_LIGHTS  1
#macro CB_LIGHTING_ONE_SHADOWED_LIGHT  2
#macro CB_LIGHTING_DEFERRED            3