#macro CB_DEFAULT_DEFERRED_LIGHT_WIDTH   512
#macro CB_DEFAULT_DEFERRED_LIGHT_HEIGHT  512

#macro CB_DEFAULT_DIRECTIONAL_LIGHT_WIDTH   1024
#macro CB_DEFAULT_DIRECTIONAL_LIGHT_HEIGHT  1024

#macro CB_CULLING_DIRECTION            cull_clockwise
#macro CB_DEPTH_MAP_CULLING_DIRECTION  cull_noculling