#macro CB_DEFAULT_DEFERRED_LIGHT_WIDTH   512
#macro CB_DEFAULT_DEFERRED_LIGHT_HEIGHT  512

#macro CB_DEFAULT_DIRECTIONAL_LIGHT_WIDTH   2048
#macro CB_DEFAULT_DIRECTIONAL_LIGHT_HEIGHT  2048

#macro CB_BACKFACE_CULLING_DIRECTION   cull_clockwise
#macro CB_DEPTH_MAP_CULLING_DIRECTION  cull_counterclockwise