//Size of `UggPoint()`.
#macro UGG_POINT_RADIUS  2

//Default thickness of `UggLine()`.
#macro UGG_LINE_THICKNESS  2

//Default base colour for Ugg's shapes. This macro will be ignored if Ugg shaders are not in use
//and `UGG_SET_FOG_TO_COLOR` has been set to `false`. In this situation, all shapes will be white.
#macro UGG_DEFAULT_DIFFUSE_COLOR  c_white

//Whether to force wireframe drawing on or off. Set this macro to `undefined` to allow wireframe
//drawing to be toggled by `UggSetWireframe()` or by functions themselves.
#macro UGG_FORCE_WIREFRAME  undefined

//Whether to force Ugg shader usage drawing on or off. Set this macro to `undefined` to allow
//Ugg shader usage to be toggled by `UggSetUseShaders()`.
/// 
/// N.B. Disabling shaders will also disable Ugg's basic system.
#macro UGG_FORCE_USE_SHADERS  undefined

//Whether to set the fog colour to the shape colour when Ugg shaders are not in use. This allows
//shapes to be drawn in colour even if Ugg shaders are disabled.
//
//N.B. This setting will overwrite the fog value. Prior fog values will not be restored and will
//     instead be overwritten.
#macro UGG_SET_FOG_TO_COLOR  true

//Parameters for Ugg's in-built light source, enabled when using Ugg's shaders. This light is used
//to give extra depth to shapes which helps with legibility.
#macro UGG_AMBIENT_LIGHT_COLOR    c_gray
#macro UGG_LIGHT_COLOR            c_white
#macro UGG_LIGHT_DIRECTION_X      -0.4
#macro UGG_LIGHT_DIRECTION_Y      -0.6
#macro UGG_LIGHT_DIRECTION_Z      -0.8

//Number of facets on smooth shapes. Higher numbers are smoother, lower numbers are faser.
#macro UGG_SPHERE_STEPS    12
#macro UGG_CYLINDER_STEPS  16
#macro UGG_CONE_STEPS      16
#macro UGG_CAPSULE_STEPS   12
#macro UGG_CIRCLE_STEPS    24

//Size of `UggPlane()`. Planes will follow the camera; this value will usually want to be equal to
//your projection's z-far.
#macro UGG_PLANE_SIZE  10_000

//Length of a line generated by `UggRay()`. This should be some arbitrary large number.
#macro UGG_RAY_LENGTH  100_000